erp/erp/urls.py
from django.contrib import admin
from django.urls import path
from dashboard.views import (
    dashboard_view,
)
from login.views import (
    login_view,
    logout_view
)
from inventory.views import (
    rawmaterials_view,
    tools_view
)
from projects.views import projects_view

admin.site.site_header = "Enterprise Resource Planning"
admin.site.site_title = "Admin - Enterprise Resource Planning"
admin.site.index_title = "Welcome to Admin - ERP portal"

urlpatterns = [
    path('', login_view, name='login'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('inventory/tools/', tools_view, name='tools'),
    path('inventory/rawmaterials/', rawmaterials_view, name='rawmaterials'),
    path('projects/', projects_view, name='projects'),
    path('admin/', admin.site.urls),
]

erp/dashboard/models.py
from django.db import models

# Create your models here.

erp/inventory/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.conf import settings
from projects.models import Projects


def get_sentinel_user():
    return get_user_model().objects.get(id=1)


class Inventory (models.Model):
    name = models.CharField('Name', max_length=100, unique=True)
    project = models.ForeignKey(Projects, on_delete=models.DO_NOTHING, null=True, blank=True, limit_choices_to=~Q(project_status=2), verbose_name='Projects\'s Name')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET(get_sentinel_user))

    class Meta:
        abstract = True

    def __str__(self):
        try:
            i = int(self.project.project_status)
            status = Projects.status[i][1]
        except AttributeError:
            status = 'available'

        if status == 'available':
            return '{} is available'.format(str(self.name))
        else:
            return '{} is being used in {}'.format(str(self.name), self.project.project_name)

    # This function is used to split the project_name in the template
    def split(self):
        return self.project.project_name.split('is')


class RawMaterials(Inventory):
    class Meta:
        db_table = 'RawMaterials'
        verbose_name_plural = 'RawMaterials'
        ordering = ['id']


class Tools(Inventory):
    class Meta:
        db_table = 'Tools'
        verbose_name_plural = 'Tools'
        ordering = ['id']

erp/login/models.py
from django.db import models

erp/projects/models.py
from django.db import models


# Create your models here.
class Projects(models.Model):
	status = [
		('0', 'Paused'),
		('1', 'On Going'),
		('2', 'Done'),
	]
	project_name = models.CharField('Project\'s Name', max_length=100, unique=True)
	project_status = models.CharField('Projects\'s Status ', max_length=1, choices=status)

	class Meta:
		db_table = 'Projects'
		verbose_name_plural = 'Projects'

	def __str__(self):
		return '{}'.format(str(self.project_name))

	def projectView(self):
		return '{} is {}'.format(str(self.project_name), str(self.status[int(str(self.project_status))][1]))

	def projectStatus(self):
		return str(self.status[int(str(self.project_status))][1])

erp/login/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField()

erp/dashboard/views.py
from django.shortcuts import render
from inventory.models import (
    RawMaterials,
    Tools
)
from projects.models import Projects


# Create your views here.
def dashboard_view(request):
    tools = Tools.objects.all().order_by('-id')
    materials = RawMaterials.objects.all().order_by('-id')
    projects = Projects.objects.all().order_by('-id')
    return render(request, 'dashboard/dashboard.html', {'tools': tools, 'materials': materials, 'projects': projects})

erp/inventory/views.py
from django.shortcuts import render
from .models import (
    Tools,
    RawMaterials
)


# Create your views here.
def tools_view(request):
    tools = Tools.objects.all()
    return render(request, 'inventory/tools.html', {'tools': tools})


def rawmaterials_view(request):
    materials = RawMaterials.objects.all()
    return render(request, 'inventory/rawmaterials.html', {'materials': materials})

erp/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def login_view(request):
    # form = LoginForm(request.POST or None)
    # if form.is_valid():
    #     username = form.cleaned_data.get('username')
    #     password = form.cleaned_data.get('password')
    #     user = authenticate(request, username=username, password=password)
    #     if user is None:
    #         return render(request, 'login/login.html', {'error_message': '*Invalid username or password '})
    #     else:
    #         login(request, user)
    #         return redirect('/dashboard/')
    # return render(request, 'login/login.html', {})
    if request.POST:
        response = request.POST
        username = response.get('username')
        password = response.get('password')
        user = authenticate(request, username=username, password=password)
        if user is None:
            return render(request, 'login/login.html', {'error_message': '*Invalid username or password '})
        else:
            login(request, user)
            return redirect('/dashboard/')
    else:
        if request.user.is_authenticated:
            return redirect('/dashboard/')
        else:
            return render(request, 'login/login.html', {'error_message': ''})


def logout_view(request):
    logout(request)
    return redirect("/login/")

erp/projects/views.py
from django.shortcuts import render
from .models import Projects


# Create your views here.
def projects_view(request):
    projects = Projects.objects.all()
    return render(request, 'project/project.html', {'projects': projects})

erp/templates/dashboard/dashboard.html
{% extends 'main/base.html' %} {% block content %}
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- 1st ROW -->
<div class="row">
  <div class="col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-warning elevation-1"
        ><i class="fas fa-tools"></i
      ></span>

      <div class="info-box-content">
        <span class="info-box-text">Tools</span>
        <span class="info-box-number">
          {{tools.count}}
          <small></small>
        </span>
      </div>
    </div>
    <!-- <div class="info-box mb-3 bg-warning">
      <span class="info-box-icon">
        <i class="fas fa-tools"></i>
      </span>
      <div class="info-box-content">
        <span class="info-box-text">Tools</span>
        <span class="info-box-number">{{tools.count}}</span>
      </div>
    </div> -->
  </div>

  <div class="col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-success elevation-1"
        ><i class="fas fa-recycle"></i
      ></span>

      <div class="info-box-content">
        <span class="info-box-text">Raw Materials</span>
        <span class="info-box-number">
          {{materials.count}}
          <small></small>
        </span>
      </div>
    </div>
    <!-- <div class="info-box mb-3 bg-success">
      <span class="info-box-icon">
        <i class="far fa-heart"></i>
      </span>
      <div class="info-box-content">
        <span class="info-box-text">Raw Materials</span>
        <span class="info-box-number">{{materials.count}}</span>
      </div>
    </div> -->
  </div>

  <div class="col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-danger elevation-1">
        <i class="fas fa-project-diagram"></i>
      </span>

      <div class="info-box-content">
        <span class="info-box-text">Projects</span>
        <span class="info-box-number">
          {{projects.count}}
          <small></small>
        </span>
      </div>
    </div>
    <!-- <div class="info-box mb-3 bg-danger">
      <span class="info-box-icon">
        <i class="fas fa-project-diagram"></i>
      </span>
      <div class="info-box-content">
        <span class="info-box-text">Projects</span>
        <span class="info-box-number">{{projects.count}}</span>
      </div>
    </div> -->
  </div>

  <div class="col-md-3">
    <div class="info-box">
      <span class="info-box-icon bg-info elevation-1"
        ><i class="fas fa-users"></i
      ></span>

      <div class="info-box-content">
        <span class="info-box-text">Unknown</span>
        <span class="info-box-number">
          {{Unknown.count}}
          <small></small>
        </span>
      </div>
    </div>
    <!-- <div class="info-box mb-3 bg-info">
      <span class="info-box-icon">
        <i class="far fa-comment"></i>
      </span>
      <div class="info-box-content">
        <span class="info-box-text">Unknown</span>
        <span class="info-box-number">{{Unknown.count}}</span>
      </div>
    </div> -->
  </div>
</div>
<!-- /.ROW -->

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header border-transparent">
        <h3 class="card-title">Latest Projects</h3>
        <div class="card-tools">
          <button
            class="btn btn-tool"
            data-card-widget="collapse"
            type="button"
          >
            <i class="fas fa-minus"></i>
          </button>
          <button class="btn btn-tool" data-card-widget="remove" type="button">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <div class="table-responsive table-bordered">
          <table class="table m-0" style="font-size: large">
            <thead>
              <tr>
                <th># ID</th>
                <th>Project</th>
                <th>Progress</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% for project in projects %} {% if forloop.counter <= 5 %}
              <tr>
                <td>
                  {% if perms.project.change_projects %}
                  <a
                    href="/admin/projects/projects/{{project.id}}/change/"
                    target="_blank"
                    >PT_{{project.id}}</a
                  >
                  {% else %}
                  <a href="#">PT_{{project.id}}</a>
                  {% endif %}
                </td>
                <td>{{project.project_name}}</td>
                {% if project.projectStatus == 'Done' %}
                <td style="vertical-align: middle">
                  <div class="progress progress-m">
                    <div
                      class="progress-bar progress-bar-striped bg-success"
                      style="width: 100%; border-radius: 5px"
                    >
                      100%
                    </div>
                  </div>
                </td>
                <td style="text-align: center; width: 12%">
                  <span
                    class="badge badge-success"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    {{project.projectStatus}}
                  </span>
                </td>
                {% elif project.projectStatus == 'Paused' %}
                <td style="vertical-align: middle">
                  <div class="progress progress-m">
                    <div
                      class="progress-bar progress-bar-striped progress-bar-animated bg-info"
                      style="width: 60%; border-radius: 5px"
                    >
                      60%
                    </div>
                  </div>
                </td>
                <td style="text-align: center; width: 12%">
                  <span
                    class="badge badge-info"
                    style="
                      width: 100%;
                      color: white;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    {{project.projectStatus}}
                  </span>
                </td>
                {% else %}
                <td style="vertical-align: middle">
                  <div class="progress progress-m">
                    <div
                      class="progress-bar progress-bar-striped progress-bar-animated bg-danger"
                      style="width: 20%; border-radius: 5px"
                    >
                      20%
                    </div>
                  </div>
                </td>
                <td style="text-align: center; width: 12%">
                  <span
                    class="badge badge-danger"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    {{project.projectStatus}}
                  </span>
                </td>
                {% endif %}
              </tr>
              {% endif %} {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix"></div>
      <!-- /.card-footer -->
    </div>
    <!-- /.card -->
  </div>
</div>

<!-- 2nd ROW -->
<div class="row">
  <!-- LEFT COL -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header border-transparent">
        <h3 class="card-title">Latest Tools</h3>
        <div class="card-tools">
          <button
            class="btn btn-tool"
            data-card-widget="collapse"
            type="button"
          >
            <i class="fas fa-minus"></i>
          </button>
          <button class="btn btn-tool" data-card-widget="remove" type="button">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <div class="table-responsive table-bordered">
          <table class="table m-0" style="font-size: large">
            <thead>
              <tr>
                <th># ID</th>
                <th>Item</th>
                <th>Status</th>
                <th>User</th>
              </tr>
            </thead>
            <tbody>
              {% for tool in tools %} {% if forloop.counter <= 5 %}
              <tr>
                <td>
                  {% if perms.inventory.change_tools %}
                  <a
                    href="/admin/inventory/tools/{{tool.id}}/change/"
                    target="_blank"
                    >TL_{{tool.id}}</a
                  >
                  {% else %}
                  <a href="#">TL_{{tool.id}}</a>
                  {% endif %}
                </td>
                <td>{{tool.name}}</td>
                <td>
                  {% if tool.project is None %}
                  <span
                    class="badge badge-success"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    Available
                  </span>
                  {% else %}
                  <span
                    class="badge badge-danger"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    <!--    To Call the function that defined in inventory.models and will split the project name from "fenyr_1 is on going" to just "fenyr_1" -->
                    {% for project_name in tool.split %} Assigned to
                    {{project_name}} {% endfor %}
                  </span>
                  {% endif %}
                </td>
                <td>
                  <div class="sparkbar" data-color="#00a65a" data-height="20">
                    {{tool.user}}
                  </div>
                </td>
              </tr>
              {% endif %} {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix"></div>
      <!-- /.card-footer -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /.col -->

  <!-- RIGHT COL -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-header border-transparent">
        <h3 class="card-title">Latest Raw Materials</h3>
        <div class="card-tools">
          <button
            class="btn btn-tool"
            data-card-widget="collapse"
            type="button"
          >
            <i class="fas fa-minus"></i>
          </button>
          <button class="btn btn-tool" data-card-widget="remove" type="button">
            <i class="fas fa-times"></i>
          </button>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <div class="table-responsive table-bordered">
          <table class="table m-0" style="font-size: large">
            <thead>
              <tr>
                <th># ID</th>
                <th>Item</th>
                <th>Status</th>
                <th>User</th>
              </tr>
            </thead>
            <tbody>
              {% for material in materials %} {% if forloop.counter <= 5 %}
              <tr>
                <td>
                  {% if perms.inventory.change_rawmaterials %}
                  <a
                    href="/admin/inventory/rawmaterials/{{material.id}}/change/"
                    target="_blank"
                    >ML_{{material.id}}</a
                  >
                  {% else %}
                  <a href="#">ML_{{material.id}}</a>
                  {% endif %}
                </td>
                <td>{{material.name}}</td>
                <td>
                  {% if material.project is None %}
                  <span
                    class="badge badge-success"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    Available
                  </span>
                  {% else %}
                  <span
                    class="badge badge-danger"
                    style="
                      width: 100%;
                      font-size: 100%;
                      font-weight: 500;
                      padding: 4%;
                    "
                  >
                    <!--    To Call the function that defined in inventory.models and will split the project name from "fenyr_1 is on going" to just "fenyr_1" -->
                    {% for project_name in material.split %} Assigned to
                    {{project_name}} {% endfor %}
                  </span>
                  {% endif %}
                </td>
                <td>
                  <div class="sparkbar" data-color="#00a65a" data-height="20">
                    {{material.user}}
                  </div>
                </td>
              </tr>
              {% endif %} {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix"></div>
      <!-- /.card-footer -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /.col -->
</div>
<!-- /.ROW -->

{% endblock %}

erp/templates/inventory/rawmaterials.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header border-transparent"><h3 class="card-title">Raw Materials</h3>
        <div class="card-tools">
            <button class="btn btn-tool" data-card-widget="collapse" type="button"
            ><i class="fas fa-minus"></i>
            </button>
            <button class="btn btn-tool" data-card-widget="remove" type="button"
            ><i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th># ID</th>
                    <th>Item</th>
                    <th>Status</th>
                    <th>User</th>
                    {% if perms.inventory.change_rawmaterials or perms.inventory.delete_rawmaterials %}
                        <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for material in materials %}
                <tr>
                    <td>
                        {% if perms.inventory.change_rawmaterials %}
                            <a href="/admin/inventory/rawmaterials/{{material.id}}/change/" target='_blank'>{{forloop.counter}}</a>
                        {% else %}
                            <a href="#">{{material.id}}</a>
                        {% endif %}
                    </td>
                    <td>
                        {{material.name}}
                    </td>
                    <td style="width: 20%; text-align: center;">
                        {% if material.project is None %}
                        <span class="badge badge-success" style="width: 100%; font-size: 100%; font-weight: 500; padding: 4%; white-space: normal;">
                            Available
                        </span>
                        {% else %}
                        <span class="badge badge-danger" style="width: 100%; font-size: 100%; font-weight: 500; padding: 4%;  white-space: normal;">
                            <!--    To Call the function that defined in inventory.models and will split the project name from "fenyr_1 is on going" to just "fenyr_1" -->
                            {% for project_name in material.split %}
                                Assigned to {{project_name}}
                            {% endfor %}
                        </span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                            {{material.user}}
                        </div>
                    </td>
                    {% if perms.inventory.change_rawmaterials or perms.inventory.delete_rawmaterials %}
                        <td>
                            {% if perms.inventory.change_rawmaterials %}
                                <a href="/admin/inventory/rawmaterials/{{material.id}}/change/" target='_blank' class="btn edit-btn" data-toggle="tooltip" data-placement="bottom" title="Edit Details">&nbsp;</a>
                            {% endif %}
                            {% if perms.inventory.delete_rawmaterials %}
                                <a href="/admin/inventory/rawmaterials/{{material.id}}/delete/" target='_blank' class="btn delete-btn" onclick="deleteApplication()" data-toggle="tooltip" data-placement="bottom" title="Delete"></a>
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div><!-- /.table-responsive -->
    <!-- /.card-body -->
    <div class="card-footer clearfix">
    </div>
    <!-- /.card-footer -->
</div><!-- /.card -->
{% endblock %}

erp/templates/inventory/tools.html
{% extends 'main/base.html' %}

{% block content %}
<div class="card">
    <div class="card-header border-transparent"><h3 class="card-title">Tools</h3>
        <div class="card-tools">
            <button class="btn btn-tool" data-card-widget="collapse" type="button"
            ><i class="fas fa-minus"></i>
            </button>
            <button class="btn btn-tool" data-card-widget="remove" type="button"
            ><i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th># ID</th>
                    <th>Item</th>
                    <th>Status</th>
                    <th>User</th>
                    {% if perms.inventory.change_tools or perms.inventory.delete_tools %}
                        <th>Actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for tool in tools %}
                <tr>
                    <td>
                        {% if perms.inventory.change_tools %}
                            <a href="/admin/inventory/tools/{{tool.id}}/change/" target='_blank'>{{forloop.counter}}</a>
                        {% else %}
                            <a href="#">{{tool.id}}</a>
                        {% endif %}
                    </td>
                    <td>
                        {{tool.name}}
                    </td>
                    <td style="width: 20%; text-align: center;">
                        {% if tool.project is None %}
                        <span class="badge badge-success" style="width: 100%; font-size: 100%; font-weight: 500; padding: 4%; white-space: normal;">
                            Available
                        </span>
                        {% else %}
                        <span class="badge badge-danger" style="width: 100%; font-size: 100%; font-weight: 500; padding: 4%; white-space: normal;">
                            <!--    To Call the function that defined in inventory.models and will split the project name from "fenyr_1 is on going" to just "fenyr_1" -->
                            {% for project_name in tool.split %}
                                Assigned to {{project_name}}
                            {% endfor %}
                        </span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="sparkbar" data-color="#00a65a" data-height="20">
                            {{tool.user}}
                        </div>
                    </td>
                    {% if perms.inventory.change_tools or perms.inventory.delete_tools %}
                        <td>
                            {% if perms.inventory.change_tools %}
                                <a href="/admin/inventory/tools/{{tool.id}}/change/" target='_blank' class="btn edit-btn" data-toggle="tooltip" data-placement="bottom" title="Edit Details">&nbsp;</a>
                            {% endif %}
                            {% if perms.inventory.delete_tools %}
                                <a href="/admin/inventory/tools/{{tool.id}}/delete/" target='_blank' class="btn delete-btn" onclick="deleteApplication()" data-toggle="tooltip" data-placement="bottom" title="Delete"></a>
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div><!-- /.table-responsive -->
    <!-- /.card-body -->
    <div class="card-footer clearfix">
    </div>
    <!-- /.card-footer -->
</div><!-- /.card -->
{% endblock %}

erp/templates/project/project.html
{% extends 'main/base.html' %} {% block content %}
<div class="card">
  <div class="card-header border-transparent">
    <h3 class="card-title">Projects</h3>
    <div class="card-tools">
      <button class="btn btn-tool" data-card-widget="collapse" type="button">
        <i class="fas fa-minus"></i>
      </button>
      <button class="btn btn-tool" data-card-widget="remove" type="button">
        <i class="fas fa-times"></i>
      </button>
    </div>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table id="table" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th># ID</th>
          <th>Project</th>
          <th>Progress</th>
          <th style="width: 12%;">Status</th>
          {% if perms.projects.change_projects or perms.projects.delete_projects %}
          <th style="width: 12%;">Actions</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for project in projects %}
        <tr>
          <td>
            {% if perms.projects.change_projects %}
                <a href="/admin/inventory/projects/projects/{{project.id}}/change/" target="_blank">
                    {{forloop.counter}}
                </a>
            {% else %}
                <a href="#">
                    {{project.id}}
                </a>
            {% endif %}
          </td>
          <td>{{project.project_name}}</td>
          {% if project.projectStatus == 'Done' %}
          <td style="vertical-align: middle">
            <div class="progress progress-m">
              <div class="progress-bar progress-bar-striped bg-success" style="width: 100%; border-radius: 5px">
                100%
              </div>
            </div>
          </td>
          <td style="text-align: center;">
            <span class="badge badge-success" style="width: 100%; font-size: 100%; font-weight: 500; padding: 4%;">
              {{project.projectStatus}}
            </span>
          </td>
          {% elif project.projectStatus == 'Paused' %}
          <td style="vertical-align: middle">
            <div class="progress progress-m">
              <div class="progress-bar progress-bar-striped progress-bar-animated bg-info" style="width: 60%; border-radius: 5px">
                60%
              </div>
            </div>
          </td>
          <td style="text-align: center; width: 12%">
            <span class="badge badge-info" style=" width: 100%; color: white; font-size: 100%; font-weight: 500; padding: 4%;">
              {{project.projectStatus}}
            </span>
          </td>
          {% else %}
          <td style="vertical-align: middle">
            <div class="progress progress-m">
              <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" style="width: 20%; border-radius: 5px">
                20%
              </div>
            </div>
          </td>
          <td style="text-align: center; width: 12%">
            <span class="badge badge-danger" style=" width: 100%; font-size: 100%; font-weight: 500; padding: 4%;">
              {{project.projectStatus}}
            </span>
          </td>
          {% endif %} 
          {% if perms.projects.change_projects or perms.projects.delete_projects %}
          <td>
            {% if perms.projects.change_projects %}
            <a href="/admin/inventory/projects/{{project.id}}/change/" target="_blank" class="btn edit-btn" data-toggle="tooltip" data-placement="bottom" title="Edit Details">&nbsp;</a>
            {% endif %} 
            
            {% if perms.projects.delete_projects %}
            <a href="/admin/inventory/projects/{{project.id}}/delete/" target="_blank" class="btn delete-btn" onclick="deleteApplication()" data-toggle="tooltip" data-placement="bottom" title="Delete"></a>
            {% endif %}
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- /.table-responsive -->
  <!-- /.card-body -->
  <div class="card-footer clearfix"></div>
  <!-- /.card-footer -->
</div>
<!-- /.card -->
{% endblock %}